[2024-10-01T20:08:14.428+0700] {processor.py:186} INFO - Started process (PID=52195) to work on /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:08:14.429+0700] {processor.py:914} INFO - Processing file /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:08:14.429+0700] {logging_mixin.py:190} INFO - [2024-10-01T20:08:14.429+0700] {dagbag.py:588} INFO - Filling up the DagBag from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:08:14.489+0700] {logging_mixin.py:190} INFO - [2024-10-01T20:08:14.489+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:08:14.489+0700] {logging_mixin.py:190} INFO - [2024-10-01T20:08:14.489+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:08:14.490+0700] {processor.py:927} WARNING - No viable dags retrieved from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:08:14.533+0700] {processor.py:208} INFO - Processing /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-10-01T20:11:01.304+0700] {processor.py:186} INFO - Started process (PID=52416) to work on /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:11:01.305+0700] {processor.py:914} INFO - Processing file /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-01T20:11:01.305+0700] {logging_mixin.py:190} INFO - [2024-10-01T20:11:01.305+0700] {dagbag.py:588} INFO - Filling up the DagBag from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:11:01.368+0700] {logging_mixin.py:190} INFO - [2024-10-01T20:11:01.368+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-01T20:11:01.368+0700] {logging_mixin.py:190} INFO - [2024-10-01T20:11:01.368+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-01T20:11:01.368+0700] {processor.py:927} WARNING - No viable dags retrieved from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-01T20:11:01.431+0700] {processor.py:208} INFO - Processing /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
