[2024-10-03T19:23:36.149+0700] {processor.py:186} INFO - Started process (PID=89955) to work on /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:23:36.150+0700] {processor.py:914} INFO - Processing file /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-03T19:23:36.150+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:23:36.150+0700] {dagbag.py:588} INFO - Filling up the DagBag from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:23:36.271+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:23:36.270+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-03T19:23:36.271+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:23:36.271+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-03T19:23:36.271+0700] {processor.py:927} WARNING - No viable dags retrieved from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:23:36.313+0700] {processor.py:208} INFO - Processing /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.169 seconds
[2024-10-03T19:26:37.115+0700] {processor.py:186} INFO - Started process (PID=90270) to work on /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:26:37.117+0700] {processor.py:914} INFO - Processing file /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-03T19:26:37.118+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:26:37.117+0700] {dagbag.py:588} INFO - Filling up the DagBag from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:26:37.192+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:26:37.191+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-03T19:26:37.192+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:26:37.192+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-03T19:26:37.192+0700] {processor.py:927} WARNING - No viable dags retrieved from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:26:37.235+0700] {processor.py:208} INFO - Processing /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.123 seconds
[2024-10-03T19:28:48.135+0700] {processor.py:186} INFO - Started process (PID=90465) to work on /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:28:48.136+0700] {processor.py:914} INFO - Processing file /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-10-03T19:28:48.137+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:28:48.137+0700] {dagbag.py:588} INFO - Filling up the DagBag from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:28:48.182+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:28:48.182+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-10-03T19:28:48.182+0700] {logging_mixin.py:190} INFO - [2024-10-03T19:28:48.182+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-10-03T19:28:48.182+0700] {processor.py:927} WARNING - No viable dags retrieved from /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-10-03T19:28:48.221+0700] {processor.py:208} INFO - Processing /Users/prabowo.kadir/.pyenv/versions/3.8.18/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
